remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: SEC4SR
description: a SECurity evaluation platform FOR Speaker Recognition
show_downloads: false
# theme: jekyll-theme-cayman

github:
  zip_url: https://github.com/SEC4SR/SEC4SR/zipball/main
  tar_url: https://github.com/SEC4SR/SEC4SR/tarball/main
  is_project_page: true
  repository_url: https://github.com/SEC4SR/SEC4SR
  repository_name: SEC4SR Platform
