title: SEC4SR
description: a SECurity evaluation platform FOR Speaker Recognition
show_downloads: false
theme: jekyll-theme-hacker

github:
  is_project_page: true
  repository_url: https://anonymous.4open.science/r/SEC4SR-AD54
  repository_name: SEC4SR Platform
