title: SEC4SR
description: a SECurity evaluation platform FOR Speaker Recognition
show_downloads: false
theme: jekyll-theme-slate

github:
  zip_url: https://github.com/SEC4SR/SEC4SR/zipball/main
  tar_url: https://github.com/SEC4SR/SEC4SR/tarball/main
  is_project_page: true
  repository_url: https://github.com/SEC4SR/SEC4SR
  repository_name: SEC4SR Platform
